// Design tokens synced with Almuzini EHR web app (artifacts/ehr/src/index.css)
// Primary: HSL(210,90%,40%) = #0A66C2  Accent: HSL(185,80%,38%) = #13A2AE

export const palette = {
  light: {
    primary: '#0A66C2',
    primaryLight: '#E8F1FB',
    primaryForeground: '#FFFFFF',
    accent: '#13A2AE',
    accentLight: '#E5F7F9',
    accentForeground: '#FFFFFF',
    background: '#F6F9FC',
    foreground: '#0D1B2A',
    card: '#FFFFFF',
    cardForeground: '#0D1B2A',
    muted: '#EEF2F7',
    mutedForeground: '#64748B',
    border: '#D6E0EC',
    input: '#D6E0EC',
    ring: '#0A66C2',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    destructiveLight: '#FEE2E2',
    success: '#16A34A',
    successLight: '#DCFCE7',
    successForeground: '#FFFFFF',
    warning: '#D97706',
    warningLight: '#FEF3C7',
    warningForeground: '#FFFFFF',
    overlay: 'rgba(0,0,0,0.5)',
    shadow: 'rgba(10,102,194,0.12)',
  },
  dark: {
    primary: '#3B8EEA',
    primaryLight: '#0F2644',
    primaryForeground: '#FFFFFF',
    accent: '#1DC0CF',
    accentLight: '#0A2D32',
    accentForeground: '#FFFFFF',
    background: '#070D1A',
    foreground: '#EDF2F7',
    card: '#0F1A2E',
    cardForeground: '#EDF2F7',
    muted: '#1B2840',
    mutedForeground: '#94A3B8',
    border: '#1E2A3A',
    input: '#1E2A3A',
    ring: '#3B8EEA',
    destructive: '#B91C1C',
    destructiveForeground: '#FEE2E2',
    destructiveLight: '#450A0A',
    success: '#15803D',
    successLight: '#14532D',
    successForeground: '#DCFCE7',
    warning: '#B45309',
    warningLight: '#451A03',
    warningForeground: '#FEF3C7',
    overlay: 'rgba(0,0,0,0.7)',
    shadow: 'rgba(0,0,0,0.3)',
  },
  radius: 12,
  radiusSm: 8,
  radiusLg: 20,
  radiusFull: 999,
  fonts: {
    regular: 'Tajawal_400Regular',
    medium: 'Tajawal_500Medium',
    bold: 'Tajawal_700Bold',
  },
} as const;

export type ThemeColors = typeof palette.light;
