export interface DrugReference {
  name: string;
  nameAr: string;
  genericName: string;
  category: string;
  categoryAr: string;
  pediatricDose: string;
  neonatalDose: string;
  route: string;
  frequency: string;
  notes?: string;
}

export const DRUG_CATEGORIES = [
  { key: "analgesic",      en: "Analgesics & Antipyretics",   ar: "مسكنات الألم وخافضات الحرارة" },
  { key: "antibiotic",     en: "Antibiotics",                 ar: "المضادات الحيوية" },
  { key: "antiviral",      en: "Antivirals & Antifungals",    ar: "مضادات الفيروسات والفطريات" },
  { key: "neurological",   en: "Neurological",                ar: "الأعصاب" },
  { key: "respiratory",    en: "Respiratory",                 ar: "الجهاز التنفسي" },
  { key: "cardiac",        en: "Cardiovascular",              ar: "القلب والأوعية الدموية" },
  { key: "gi",             en: "Gastrointestinal",            ar: "الجهاز الهضمي" },
  { key: "endocrine",      en: "Endocrine & Steroids",        ar: "الغدد الصماء والكورتيكوستيرويدات" },
  { key: "hematology",     en: "Hematology & Vitamins",       ar: "أمراض الدم والفيتامينات" },
  { key: "emergency",      en: "Emergency & Resuscitation",   ar: "الطوارئ والإنعاش" },
  { key: "fluid",          en: "IV Fluids & Electrolytes",    ar: "السوائل الوريدية والإلكتروليتات" },
];

export const DRUG_REFERENCE: DrugReference[] = [
  // ── Analgesics & Antipyretics ──────────────────────────────────────
  {
    name: "Paracetamol (Acetaminophen)",
    nameAr: "باراسيتامول",
    genericName: "Paracetamol",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "10–15 mg/kg/dose q4–6h (max 75 mg/kg/day, 4 g/day)",
    neonatalDose: "10–15 mg/kg/dose q6–8h PO; IV: 7.5 mg/kg/dose q6–8h (preterm); 10 mg/kg/dose q6–8h (term)",
    route: "PO / IV / PR",
    frequency: "q4–6h",
    notes: "Do not exceed 5 doses in 24 hours",
  },
  {
    name: "Ibuprofen",
    nameAr: "إيبوبروفين",
    genericName: "Ibuprofen",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "5–10 mg/kg/dose q6–8h (max 40 mg/kg/day; ≥6 months)",
    neonatalDose: "Not recommended in neonates (renal risk)",
    route: "PO",
    frequency: "q6–8h",
    notes: "Avoid in infants <6 months; avoid with dehydration or renal impairment",
  },
  {
    name: "Morphine Sulfate",
    nameAr: "مورفين",
    genericName: "Morphine",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "0.05–0.1 mg/kg/dose q2–4h IV/IM; infusion 0.01–0.04 mg/kg/h",
    neonatalDose: "0.05–0.1 mg/kg/dose q4–6h slow IV; infusion 0.005–0.01 mg/kg/h",
    route: "IV / IM / PO",
    frequency: "q2–6h",
    notes: "Monitor respiratory status; have naloxone available",
  },
  {
    name: "Tramadol",
    nameAr: "ترامادول",
    genericName: "Tramadol",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "1–2 mg/kg/dose q4–6h (max 8 mg/kg/day; ≥12 years)",
    neonatalDose: "Not recommended",
    route: "PO / IV",
    frequency: "q4–6h",
  },

  // ── Antibiotics ────────────────────────────────────────────────────
  {
    name: "Amoxicillin",
    nameAr: "أموكسيسيلين",
    genericName: "Amoxicillin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "25–50 mg/kg/day ÷ q8h (mild–moderate); 80–90 mg/kg/day ÷ q12h (AOM high-dose)",
    neonatalDose: "25–50 mg/kg/day ÷ q12h (0–7 days); ÷ q8h (>7 days)",
    route: "PO / IV",
    frequency: "q8–12h",
  },
  {
    name: "Co-Amoxiclav (Amoxicillin-Clavulanate)",
    nameAr: "أموكسيسيلين + حمض كلافولانيك",
    genericName: "Amoxicillin-Clavulanate",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "25–45 mg/kg/day (amoxicillin component) ÷ q12h (7:1 formulation preferred)",
    neonatalDose: "Not recommended in neonates",
    route: "PO / IV",
    frequency: "q8–12h",
    notes: "Diarrhea common; use 7:1 formulation to reduce GI effects",
  },
  {
    name: "Ampicillin",
    nameAr: "أمبيسيلين",
    genericName: "Ampicillin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "100–200 mg/kg/day ÷ q6h IV (meningitis: 300–400 mg/kg/day ÷ q4–6h)",
    neonatalDose: "50 mg/kg/dose: q12h (<7 days, <2 kg); q8h (>7 days or ≥2 kg); meningitis: q8h or q6h",
    route: "IV / IM",
    frequency: "q4–12h",
  },
  {
    name: "Benzylpenicillin (Penicillin G)",
    nameAr: "بنزيل بنسلين",
    genericName: "Benzylpenicillin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "50,000 units/kg/day ÷ q4–6h (mild); 250,000–400,000 units/kg/day ÷ q4h (meningitis)",
    neonatalDose: "50,000 units/kg/dose q12h (<7 days); q8h (7–28 days); meningitis: q6h",
    route: "IV / IM",
    frequency: "q4–12h",
  },
  {
    name: "Ceftriaxone",
    nameAr: "سيفترياكسون",
    genericName: "Ceftriaxone",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "50–100 mg/kg/day ÷ q12–24h (meningitis: 100 mg/kg/day ÷ q12h; max 4 g/day)",
    neonatalDose: "Avoid in neonates with hyperbilirubinemia; if used: 50 mg/kg/day once daily",
    route: "IV / IM",
    frequency: "q12–24h",
    notes: "Avoid with calcium-containing IV solutions in neonates",
  },
  {
    name: "Cefotaxime",
    nameAr: "سيفوتاكسيم",
    genericName: "Cefotaxime",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "100–200 mg/kg/day ÷ q6–8h (meningitis: 200–300 mg/kg/day ÷ q6h)",
    neonatalDose: "50 mg/kg/dose: q12h (<7 days); q8h (7–28 days); meningitis: q6h",
    route: "IV / IM",
    frequency: "q6–8h",
  },
  {
    name: "Cefuroxime",
    nameAr: "سيفوروكسيم",
    genericName: "Cefuroxime",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "75–150 mg/kg/day ÷ q8h IV; PO: 20–30 mg/kg/day ÷ q12h",
    neonatalDose: "30–100 mg/kg/day ÷ q12h",
    route: "IV / PO",
    frequency: "q8–12h",
  },
  {
    name: "Cephalexin",
    nameAr: "سيفاليكسين",
    genericName: "Cephalexin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "25–50 mg/kg/day ÷ q6–12h (skin/soft tissue: 25–50 mg/kg/day ÷ q6h)",
    neonatalDose: "25 mg/kg/dose q8–12h",
    route: "PO",
    frequency: "q6–12h",
  },
  {
    name: "Gentamicin",
    nameAr: "جنتاميسين",
    genericName: "Gentamicin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "5–7.5 mg/kg/day ÷ q8h (or 7.5 mg/kg once daily extended-interval)",
    neonatalDose: "4–5 mg/kg/dose: q48h (<28 wks GA); q36h (28–34 wks); q24h (≥35 wks)",
    route: "IV / IM",
    frequency: "q8–48h",
    notes: "Monitor levels (peak & trough); nephrotoxic and ototoxic",
  },
  {
    name: "Vancomycin",
    nameAr: "فانكوميسين",
    genericName: "Vancomycin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "40–60 mg/kg/day ÷ q6h IV (meningitis: 60 mg/kg/day ÷ q6h)",
    neonatalDose: "10–15 mg/kg/dose: q18–24h (<29 wks); q12h (29–36 wks); q8h (≥37 wks, >7 days)",
    route: "IV",
    frequency: "q6–24h",
    notes: "Monitor trough (15–20 mcg/mL for severe infections); infuse over ≥60 min",
  },
  {
    name: "Metronidazole",
    nameAr: "ميترونيدازول",
    genericName: "Metronidazole",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "22.5–40 mg/kg/day ÷ q8h IV/PO (max 2.25 g/day)",
    neonatalDose: "7.5 mg/kg/dose: loading 15 mg/kg then q12h (<7 days); q8h (>7 days)",
    route: "IV / PO",
    frequency: "q8h",
  },
  {
    name: "Clindamycin",
    nameAr: "كلينداميسين",
    genericName: "Clindamycin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "20–40 mg/kg/day ÷ q6–8h IV; PO: 8–25 mg/kg/day ÷ q6–8h",
    neonatalDose: "5 mg/kg/dose q8h (<7 days); q6h (>7 days)",
    route: "IV / PO",
    frequency: "q6–8h",
    notes: "Risk of Clostridioides difficile colitis",
  },
  {
    name: "Azithromycin",
    nameAr: "أزيثروميسين",
    genericName: "Azithromycin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "10 mg/kg/day once daily × 3 days (CAP); 10 mg/kg Day 1 then 5 mg/kg Days 2–5 (otitis)",
    neonatalDose: "Pertussis prophylaxis: 10 mg/kg/day once daily × 5 days",
    route: "PO / IV",
    frequency: "Once daily",
  },
  {
    name: "Clarithromycin",
    nameAr: "كلاريثروميسين",
    genericName: "Clarithromycin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "15 mg/kg/day ÷ q12h (max 1 g/day)",
    neonatalDose: "Not recommended <1 month",
    route: "PO",
    frequency: "q12h",
  },
  {
    name: "Co-trimoxazole (TMP-SMX)",
    nameAr: "كوتريموكسازول",
    genericName: "Trimethoprim-Sulfamethoxazole",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "6–12 mg/kg/day (TMP component) ÷ q12h (UTI); PCP: 15–20 mg/kg/day ÷ q6h",
    neonatalDose: "Avoid in neonates <4 weeks (risk of kernicterus)",
    route: "PO / IV",
    frequency: "q12h",
  },
  {
    name: "Ciprofloxacin",
    nameAr: "سيبروفلوكساسين",
    genericName: "Ciprofloxacin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "20–30 mg/kg/day ÷ q12h PO; 15–20 mg/kg/day ÷ q12h IV (max 1.5 g/day)",
    neonatalDose: "10–15 mg/kg/dose q12h (use only when no safer alternative)",
    route: "PO / IV",
    frequency: "q12h",
    notes: "Reserve for resistant organisms or specific indications; avoid unless necessary in children",
  },

  // ── Antivirals & Antifungals ───────────────────────────────────────
  {
    name: "Acyclovir",
    nameAr: "أسيكلوفير",
    genericName: "Acyclovir",
    category: "antiviral",
    categoryAr: "مضادات الفيروسات والفطريات",
    pediatricDose: "HSV encephalitis: 500 mg/m²/dose q8h IV (or 20 mg/kg/dose q8h); VZV: 10–15 mg/kg/dose q8h IV",
    neonatalDose: "HSV: 20 mg/kg/dose q8h IV × 14–21 days; ensure adequate hydration",
    route: "IV / PO",
    frequency: "q8h",
    notes: "Maintain adequate hydration to prevent nephrotoxicity",
  },
  {
    name: "Fluconazole",
    nameAr: "فلوكونازول",
    genericName: "Fluconazole",
    category: "antiviral",
    categoryAr: "مضادات الفيروسات والفطريات",
    pediatricDose: "6–12 mg/kg/day once daily (candidiasis); 12 mg/kg/day (invasive, max 800 mg/day)",
    neonatalDose: "3–6 mg/kg/dose: q72h (<30 wks); q48h (30–36 wks); q24h (≥37 wks)",
    route: "PO / IV",
    frequency: "Once daily",
  },
  {
    name: "Nystatin",
    nameAr: "نيستاتين",
    genericName: "Nystatin",
    category: "antiviral",
    categoryAr: "مضادات الفيروسات والفطريات",
    pediatricDose: "100,000–500,000 units PO q6h (oral thrush)",
    neonatalDose: "100,000 units PO q6h",
    route: "PO (topical/suspension)",
    frequency: "q6h",
  },

  // ── Neurological ──────────────────────────────────────────────────
  {
    name: "Phenobarbital",
    nameAr: "فينوباربيتال",
    genericName: "Phenobarbital",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "Loading: 15–20 mg/kg IV; Maintenance: 3–5 mg/kg/day ÷ q12–24h",
    neonatalDose: "Loading: 20 mg/kg IV; may repeat 10 mg/kg × 2; Maintenance: 3–5 mg/kg/day once daily",
    route: "IV / PO",
    frequency: "Loading then q12–24h",
    notes: "Monitor respiratory depression; therapeutic level 15–40 mcg/mL",
  },
  {
    name: "Phenytoin (Diphenylhydantoin)",
    nameAr: "فينيتوين",
    genericName: "Phenytoin",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "Loading: 15–20 mg/kg IV (max rate 1 mg/kg/min); Maintenance: 4–8 mg/kg/day ÷ q12h",
    neonatalDose: "Loading: 15–20 mg/kg IV; Maintenance: 4–8 mg/kg/day ÷ q12–24h",
    route: "IV / PO",
    frequency: "q12h",
    notes: "Infuse at ≤1 mg/kg/min; monitor ECG during loading",
  },
  {
    name: "Levetiracetam",
    nameAr: "ليفيتيراسيتام",
    genericName: "Levetiracetam",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "Loading: 20–60 mg/kg IV; Maintenance: 20–60 mg/kg/day ÷ q12h",
    neonatalDose: "Loading: 40–60 mg/kg IV; Maintenance: 20–40 mg/kg/day ÷ q12h",
    route: "IV / PO",
    frequency: "q12h",
  },
  {
    name: "Sodium Valproate (Valproic Acid)",
    nameAr: "صوديوم فالبروات",
    genericName: "Valproic Acid",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "Loading: 20–40 mg/kg IV; Maintenance: 20–60 mg/kg/day ÷ q8–12h",
    neonatalDose: "Not well-established; use with extreme caution (hepatotoxicity risk)",
    route: "PO / IV",
    frequency: "q8–12h",
    notes: "Hepatotoxicity risk; avoid <2 years if possible; therapeutic level 50–100 mcg/mL",
  },
  {
    name: "Carbamazepine",
    nameAr: "كاربامازيبين",
    genericName: "Carbamazepine",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "<6 years: 10–20 mg/kg/day ÷ q8–12h; 6–12 years: 100 mg q12h → titrate to 400–800 mg/day",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "q8–12h",
  },
  {
    name: "Diazepam",
    nameAr: "ديازيبام",
    genericName: "Diazepam",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "0.1–0.3 mg/kg/dose IV (max 10 mg/dose); PR: 0.5 mg/kg (max 20 mg)",
    neonatalDose: "0.1–0.3 mg/kg/dose IV slowly; may repeat q15–30 min",
    route: "IV / PR",
    frequency: "PRN (seizure rescue)",
    notes: "Give IV slowly; have resuscitation equipment available",
  },
  {
    name: "Midazolam",
    nameAr: "ميدازولام",
    genericName: "Midazolam",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "Status epilepticus: 0.1–0.2 mg/kg IV/IM/IN (max 10 mg); sedation infusion: 0.05–0.1 mg/kg/h",
    neonatalDose: "0.05–0.1 mg/kg/dose IV slowly; infusion: 0.01–0.06 mg/kg/h",
    route: "IV / IM / IN / Buccal",
    frequency: "PRN (acute) or continuous infusion",
    notes: "Monitor respiratory status; flumazenil available as reversal",
  },
  {
    name: "Lorazepam",
    nameAr: "لورازيبام",
    genericName: "Lorazepam",
    category: "neurological",
    categoryAr: "الأعصاب",
    pediatricDose: "Status epilepticus: 0.05–0.1 mg/kg IV (max 4 mg/dose)",
    neonatalDose: "0.05 mg/kg/dose IV slowly; may repeat once after 10–15 min",
    route: "IV",
    frequency: "PRN (seizure rescue)",
  },

  // ── Respiratory ───────────────────────────────────────────────────
  {
    name: "Salbutamol (Albuterol)",
    nameAr: "سالبوتامول",
    genericName: "Salbutamol",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "Nebulised: 2.5 mg (<20 kg) / 5 mg (≥20 kg) q20 min × 3 (acute); MDI: 2–4 puffs q4–6h",
    neonatalDose: "Nebulised: 0.15 mg/kg/dose q4–6h (min 2.5 mg); IV infusion: 1–5 mcg/kg/min",
    route: "Nebulised / MDI / IV",
    frequency: "q20min (acute) → q4–6h",
    notes: "Monitor heart rate and potassium; IV route for severe bronchospasm",
  },
  {
    name: "Ipratropium Bromide",
    nameAr: "إبراتروبيوم بروميد",
    genericName: "Ipratropium",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "Nebulised: 250 mcg (<5 years) / 500 mcg (≥5 years) q20 min × 3 (acute)",
    neonatalDose: "75–175 mcg/dose q8h nebulised",
    route: "Nebulised",
    frequency: "q6–8h (maintenance); q20min (acute)",
  },
  {
    name: "Aminophylline",
    nameAr: "أمينوفيلين",
    genericName: "Aminophylline",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "Loading: 5 mg/kg IV over 30 min; Maintenance infusion: 0.7–0.9 mg/kg/h",
    neonatalDose: "Apnoea: Loading 5 mg/kg IV; Maintenance: 2.5 mg/kg/dose q8–12h (target theophylline 5–10 mcg/mL)",
    route: "IV",
    frequency: "Loading then continuous infusion",
    notes: "Monitor levels (therapeutic 10–20 mcg/mL; 5–10 for apnoea of prematurity); tachycardia risk",
  },
  {
    name: "Dexamethasone",
    nameAr: "ديكساميتازون",
    genericName: "Dexamethasone",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "Croup: 0.15–0.6 mg/kg PO/IM/IV (max 10 mg) single dose; Cerebral oedema: 0.1–0.3 mg/kg/dose q6h",
    neonatalDose: "0.1–0.15 mg/kg/dose q12–24h (BPD extubation); short course only",
    route: "PO / IM / IV",
    frequency: "Single dose (croup) or q6–12h",
    notes: "Single dose for croup is usually sufficient",
  },
  {
    name: "Budesonide (Inhaled)",
    nameAr: "بوديزونيد",
    genericName: "Budesonide",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "Croup nebulised: 2 mg single dose; Asthma ICS: 100–400 mcg/day ÷ q12h",
    neonatalDose: "Nebulised: 0.5–1 mg/dose q12h (CLD/BPD)",
    route: "Nebulised / Inhaled",
    frequency: "q12h or once daily",
  },
  {
    name: "Adrenaline (Epinephrine) Nebulised",
    nameAr: "أدرينالين نبولايزد",
    genericName: "Epinephrine",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "Croup: 0.5 mL/kg of 1:1000 (max 5 mL) nebulised",
    neonatalDose: "0.1–0.3 mL/kg of 1:1000 nebulised",
    route: "Nebulised",
    frequency: "q1–4h PRN",
    notes: "Observe for rebound at least 2–4h; nebulised adrenaline for upper airway",
  },

  // ── Cardiovascular ────────────────────────────────────────────────
  {
    name: "Furosemide (Frusemide)",
    nameAr: "فوروسيميد",
    genericName: "Furosemide",
    category: "cardiac",
    categoryAr: "القلب والأوعية الدموية",
    pediatricDose: "0.5–2 mg/kg/dose q6–12h PO/IV (max 6 mg/kg/day); infusion: 0.05–0.2 mg/kg/h",
    neonatalDose: "0.5–1 mg/kg/dose PO/IV q12–24h; avoid prolonged use in premature infants",
    route: "PO / IV",
    frequency: "q6–24h",
    notes: "Monitor electrolytes (K+, Na+); ototoxicity with high doses",
  },
  {
    name: "Spironolactone",
    nameAr: "سبيرونولاكتون",
    genericName: "Spironolactone",
    category: "cardiac",
    categoryAr: "القلب والأوعية الدموية",
    pediatricDose: "1–3 mg/kg/day ÷ q12–24h PO",
    neonatalDose: "1–2 mg/kg/dose q12–24h",
    route: "PO",
    frequency: "q12–24h",
    notes: "Monitor potassium; potassium-sparing diuretic",
  },
  {
    name: "Digoxin",
    nameAr: "ديجوكسين",
    genericName: "Digoxin",
    category: "cardiac",
    categoryAr: "القلب والأوعية الدموية",
    pediatricDose: "Digitalising: 20–35 mcg/kg ÷ over 24h; Maintenance: 5–10 mcg/kg/day ÷ q12h",
    neonatalDose: "Digitalising: 20–30 mcg/kg (term) / 15–25 mcg/kg (preterm); Maintenance: 5–8 mcg/kg/day ÷ q12h",
    route: "PO / IV",
    frequency: "q12h",
    notes: "Monitor ECG and digoxin levels (0.8–2 ng/mL); narrow therapeutic window",
  },
  {
    name: "Propranolol",
    nameAr: "بروبرانولول",
    genericName: "Propranolol",
    category: "cardiac",
    categoryAr: "القلب والأوعية الدموية",
    pediatricDose: "Arrhythmia: 0.01–0.1 mg/kg IV slowly; PO: 0.5–4 mg/kg/day ÷ q6–8h",
    neonatalDose: "0.5–1 mg/kg/day ÷ q6–8h PO (haemangioma/SVT)",
    route: "PO / IV",
    frequency: "q6–8h",
    notes: "Monitor HR; contraindicated in bronchospasm; may cause hypoglycaemia",
  },
  {
    name: "Atenolol",
    nameAr: "أتينولول",
    genericName: "Atenolol",
    category: "cardiac",
    categoryAr: "القلب والأوعية الدموية",
    pediatricDose: "0.5–1 mg/kg/day PO once daily (max 2 mg/kg/day)",
    neonatalDose: "0.5–1 mg/kg/day PO once daily",
    route: "PO",
    frequency: "Once daily",
  },
  {
    name: "Adenosine",
    nameAr: "أدينوزين",
    genericName: "Adenosine",
    category: "cardiac",
    categoryAr: "القلب والأوعية الدموية",
    pediatricDose: "0.1 mg/kg rapid IV bolus; may ↑ by 0.05 mg/kg q1–2 min (max 0.3 mg/kg or 12 mg)",
    neonatalDose: "0.1 mg/kg rapid IV bolus; max 0.3 mg/kg",
    route: "IV (rapid bolus)",
    frequency: "PRN (SVT)",
    notes: "Must be given as rapid bolus followed immediately by saline flush; transient asystole expected",
  },

  // ── Gastrointestinal ──────────────────────────────────────────────
  {
    name: "Ondansetron",
    nameAr: "أوندانسيترون",
    genericName: "Ondansetron",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "0.1–0.15 mg/kg/dose PO/IV q4–8h (max 4 mg/dose <40 kg; 8 mg/dose ≥40 kg)",
    neonatalDose: "0.1 mg/kg/dose q6–8h (use with caution; QT prolongation risk)",
    route: "PO / IV",
    frequency: "q4–8h",
    notes: "QT prolongation risk with high doses; check ECG with repeated dosing",
  },
  {
    name: "Metoclopramide",
    nameAr: "ميتوكلوبراميد",
    genericName: "Metoclopramide",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "0.1–0.2 mg/kg/dose q6–8h PO/IV (max 0.5 mg/kg/day)",
    neonatalDose: "0.05–0.1 mg/kg/dose q6–8h (extrapyramidal risk — use with caution)",
    route: "PO / IV",
    frequency: "q6–8h",
    notes: "Risk of extrapyramidal effects; avoid in infants <1 month if possible",
  },
  {
    name: "Domperidone",
    nameAr: "دومبيريدون",
    genericName: "Domperidone",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "0.2–0.3 mg/kg/dose q8h PO (max 10 mg/dose)",
    neonatalDose: "0.1–0.3 mg/kg/dose q6–8h",
    route: "PO",
    frequency: "q8h",
    notes: "QT prolongation risk; avoid prolonged use",
  },
  {
    name: "Omeprazole",
    nameAr: "أوميبرازول",
    genericName: "Omeprazole",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "0.7–3.5 mg/kg/day PO once daily (GORD); IV: 0.5–1.5 mg/kg/day",
    neonatalDose: "0.5–1.5 mg/kg/day PO once daily (GORD); evidence limited in <1 month",
    route: "PO / IV",
    frequency: "Once daily",
  },
  {
    name: "Ranitidine",
    nameAr: "رانيتيدين",
    genericName: "Ranitidine",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "2–4 mg/kg/day ÷ q8–12h PO (max 300 mg/day); IV: 1–2 mg/kg/day ÷ q6–8h",
    neonatalDose: "2 mg/kg/dose q12h IV/PO",
    route: "PO / IV",
    frequency: "q8–12h",
    notes: "H2-blocker; largely replaced by PPIs for most indications",
  },
  {
    name: "Lactulose",
    nameAr: "لاكتولوز",
    genericName: "Lactulose",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "Constipation: 1–3 mL/kg/day ÷ q12–24h PO; Hepatic encephalopathy: 40–90 mL/day ÷ q6–8h",
    neonatalDose: "1–2 mL/kg/day ÷ q12h (constipation)",
    route: "PO",
    frequency: "q12–24h",
  },

  // ── Endocrine & Steroids ──────────────────────────────────────────
  {
    name: "Prednisolone",
    nameAr: "بريدنيزولون",
    genericName: "Prednisolone",
    category: "endocrine",
    categoryAr: "الغدد الصماء والكورتيكوستيرويدات",
    pediatricDose: "Asthma acute: 1–2 mg/kg/day ÷ q12–24h × 3–5 days (max 40 mg/day); Anti-inflammatory: 1–2 mg/kg/day",
    neonatalDose: "0.5–2 mg/kg/day ÷ q12h (CAH, anti-inflammatory; use with caution)",
    route: "PO",
    frequency: "q12–24h",
  },
  {
    name: "Hydrocortisone",
    nameAr: "هيدروكورتيزون",
    genericName: "Hydrocortisone",
    category: "endocrine",
    categoryAr: "الغدد الصماء والكورتيكوستيرويدات",
    pediatricDose: "Stress dosing: 50 mg/m²/day ÷ q6–8h; Adrenal crisis: 50–100 mg/m² bolus then 50–100 mg/m²/day",
    neonatalDose: "Adrenal insufficiency: 10–15 mg/m²/day ÷ q8h; hypotension: 1–3 mg/kg/dose q6–12h IV",
    route: "IV / PO",
    frequency: "q6–8h",
  },
  {
    name: "Insulin (Regular)",
    nameAr: "إنسولين عادي",
    genericName: "Insulin Regular",
    category: "endocrine",
    categoryAr: "الغدد الصماء والكورتيكوستيرويدات",
    pediatricDose: "DKA: 0.05–0.1 units/kg/h IV infusion; Hyperglycaemia: 0.05–0.1 units/kg SC q4–6h",
    neonatalDose: "Hyperglycaemia: 0.01–0.05 units/kg/h IV infusion",
    route: "IV infusion / SC",
    frequency: "Continuous infusion or q4–6h SC",
    notes: "Monitor blood glucose hourly during infusion; DKA protocol",
  },

  // ── Hematology & Vitamins ─────────────────────────────────────────
  {
    name: "Iron (Ferrous Sulfate)",
    nameAr: "كبريتات الحديد",
    genericName: "Ferrous Sulfate",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Therapeutic (IDA): 3–6 mg/kg/day elemental iron ÷ q8–24h PO; Prophylactic: 1–2 mg/kg/day",
    neonatalDose: "Premature: 2–4 mg/kg/day elemental iron from 4–6 weeks of age; Term: 1 mg/kg/day from 4 months",
    route: "PO",
    frequency: "q8–24h",
    notes: "Give on empty stomach if tolerated; stains teeth (use straw or dilute); check Hgb in 4–6 weeks",
  },
  {
    name: "Vitamin D (Cholecalciferol)",
    nameAr: "فيتامين د",
    genericName: "Cholecalciferol",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Deficiency treatment: 1000–5000 IU/day × 6–12 weeks; Prophylaxis: 400–600 IU/day",
    neonatalDose: "400–800 IU/day (prophylaxis from first week of life); 1000–2000 IU/day if deficient",
    route: "PO",
    frequency: "Once daily",
  },
  {
    name: "Vitamin K (Phytomenadione)",
    nameAr: "فيتامين ك",
    genericName: "Phytomenadione",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Haemorrhagic disease prophylaxis: 1 mg IM at birth; deficiency bleeding: 1–10 mg IV/IM",
    neonatalDose: "≥1 kg: 1 mg IM at birth; <1 kg: 0.5 mg IM at birth",
    route: "IM / IV / PO",
    frequency: "Single dose (prophylaxis) or per response",
  },
  {
    name: "Folic Acid",
    nameAr: "حمض الفوليك",
    genericName: "Folic Acid",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Megaloblastic anaemia: 1–5 mg/day PO; Prophylaxis: 0.1–0.5 mg/day",
    neonatalDose: "50 mcg/day PO (supplementation)",
    route: "PO",
    frequency: "Once daily",
  },
  {
    name: "Zinc Sulfate",
    nameAr: "كبريتات الزنك",
    genericName: "Zinc Sulfate",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Diarrhoea (WHO): 10 mg/day (<6 months); 20 mg/day (≥6 months) × 10–14 days; Deficiency: 0.5–1 mg/kg/day",
    neonatalDose: "1 mg/kg/day elemental zinc PO (preterm/deficiency)",
    route: "PO",
    frequency: "Once daily",
  },

  // ── Emergency & Resuscitation ─────────────────────────────────────
  {
    name: "Adrenaline (Epinephrine) IV/IO",
    nameAr: "أدرينالين للحقن",
    genericName: "Epinephrine",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Cardiac arrest: 0.01 mg/kg (0.1 mL/kg of 1:10,000) IV/IO q3–5 min; Anaphylaxis IM: 0.01 mg/kg 1:1000 (max 0.5 mg)",
    neonatalDose: "Cardiac arrest: 0.01–0.03 mg/kg (0.1–0.3 mL/kg of 1:10,000) IV/IO q3–5 min",
    route: "IV / IO / IM",
    frequency: "q3–5 min (arrest) / single dose IM (anaphylaxis)",
    notes: "PALS/NLS dose; confirm concentration carefully",
  },
  {
    name: "Atropine",
    nameAr: "أتروبين",
    genericName: "Atropine",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Bradycardia: 0.02 mg/kg IV (min 0.1 mg; max 0.5 mg child / 1 mg adolescent); may repeat once",
    neonatalDose: "0.02 mg/kg/dose IV; min 0.1 mg",
    route: "IV / IM / ET",
    frequency: "PRN (bradycardia)",
    notes: "Minimum dose 0.1 mg to avoid paradoxical bradycardia",
  },
  {
    name: "Dopamine",
    nameAr: "دوبامين",
    genericName: "Dopamine",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "2–20 mcg/kg/min IV infusion (dopaminergic: 2–5; inotrope: 5–10; vasopressor: >10 mcg/kg/min)",
    neonatalDose: "2–20 mcg/kg/min IV infusion; start at 2–5 mcg/kg/min",
    route: "IV infusion",
    frequency: "Continuous infusion",
    notes: "Central line preferred; extravasation causes tissue necrosis — use phentolamine if occurs",
  },
  {
    name: "Dobutamine",
    nameAr: "دوبوتامين",
    genericName: "Dobutamine",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "5–20 mcg/kg/min IV infusion (primarily inotrope; tachycardia at higher doses)",
    neonatalDose: "2–20 mcg/kg/min IV infusion; start at 5 mcg/kg/min",
    route: "IV infusion",
    frequency: "Continuous infusion",
  },
  {
    name: "Noradrenaline (Norepinephrine)",
    nameAr: "نورأدرينالين",
    genericName: "Norepinephrine",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "0.1–2 mcg/kg/min IV infusion (titrate to MAP target)",
    neonatalDose: "0.05–1 mcg/kg/min IV infusion",
    route: "IV infusion (central line)",
    frequency: "Continuous infusion",
    notes: "Requires central venous access; causes severe tissue necrosis if extravasated",
  },
  {
    name: "Sodium Bicarbonate",
    nameAr: "بيكربونات الصوديوم",
    genericName: "Sodium Bicarbonate",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Metabolic acidosis: 1–2 mEq/kg IV slow push (4.2% solution in neonates); use BE × weight × 0.3",
    neonatalDose: "1–2 mEq/kg IV slow push of 4.2% (0.5 mEq/mL) over ≥2 min",
    route: "IV",
    frequency: "Per deficit",
    notes: "Use 4.2% (diluted) in neonates; confirm ventilation is adequate before giving",
  },
  {
    name: "Calcium Gluconate",
    nameAr: "غلوكونات الكالسيوم",
    genericName: "Calcium Gluconate",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Hypocalcaemia: 0.5–1 mL/kg of 10% solution IV slowly (max 20 mL); maintenance: 200–500 mg/kg/day",
    neonatalDose: "Symptomatic hypocalcaemia: 1–2 mL/kg of 10% IV over 10 min; maintenance: 200–800 mg/kg/day",
    route: "IV",
    frequency: "PRN or continuous infusion",
    notes: "Monitor ECG during infusion; risk of bradycardia if given too fast",
  },
  {
    name: "Glucose (Dextrose) 10%",
    nameAr: "جلوكوز 10٪",
    genericName: "Dextrose 10%",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Hypoglycaemia: 2–5 mL/kg IV bolus (= 0.2–0.5 g/kg); maintenance GIR: 4–8 mg/kg/min",
    neonatalDose: "2–4 mL/kg of 10% dextrose IV bolus; then maintain GIR 6–8 mg/kg/min (min)",
    route: "IV",
    frequency: "PRN bolus then continuous infusion",
  },
  {
    name: "Naloxone",
    nameAr: "نالوكسون",
    genericName: "Naloxone",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Opioid reversal: 0.01–0.1 mg/kg IV/IM/IN (max 2 mg); repeat q2–3 min PRN",
    neonatalDose: "0.01 mg/kg IV/IM; may repeat q2–3 min; continuous infusion if needed: 0.002–0.16 mg/kg/h",
    route: "IV / IM / SC / IN",
    frequency: "q2–3 min PRN",
    notes: "Duration shorter than most opioids; monitor for re-narcotisation",
  },

  // ── IV Fluids ─────────────────────────────────────────────────────
  {
    name: "Normal Saline (0.9% NaCl)",
    nameAr: "محلول ملحي طبيعي",
    genericName: "Sodium Chloride 0.9%",
    category: "fluid",
    categoryAr: "السوائل الوريدية والإلكتروليتات",
    pediatricDose: "Bolus (sepsis/shock): 10–20 mL/kg IV over 5–30 min (reassess; max 60 mL/kg total)",
    neonatalDose: "Bolus: 10 mL/kg IV over 30–60 min; maintenance per Holliday-Segar",
    route: "IV",
    frequency: "PRN bolus or continuous infusion",
  },
  {
    name: "Ringer's Lactate",
    nameAr: "رينجر لاكتات",
    genericName: "Lactated Ringer's",
    category: "fluid",
    categoryAr: "السوائل الوريدية والإلكتروليتات",
    pediatricDose: "Resuscitation: 10–20 mL/kg IV bolus; preferred in trauma/DKA (avoids hyperchloraemic acidosis)",
    neonatalDose: "10 mL/kg IV over 30–60 min (sepsis/shock)",
    route: "IV",
    frequency: "PRN bolus or continuous infusion",
  },
  {
    name: "Potassium Chloride (KCl)",
    nameAr: "كلوريد البوتاسيوم",
    genericName: "Potassium Chloride",
    category: "fluid",
    categoryAr: "السوائل الوريدية والإلكتروليتات",
    pediatricDose: "Hypokalaemia: 0.5–1 mEq/kg IV over 1h (severe); oral: 1–4 mEq/kg/day ÷ q6–12h",
    neonatalDose: "Add to IV fluids: 2–4 mEq/kg/day; never give undiluted IV push",
    route: "IV (diluted) / PO",
    frequency: "Per deficit or maintenance",
    notes: "NEVER give undiluted IV push — fatal; max peripheral concentration 40 mEq/L",
  },
  {
    name: "ORS (Oral Rehydration Salts)",
    nameAr: "محلول إماهة فموي",
    genericName: "Oral Rehydration Solution",
    category: "fluid",
    categoryAr: "السوائل الوريدية والإلكتروليتات",
    pediatricDose: "Mild dehydration: 50 mL/kg over 4h; Moderate: 100 mL/kg over 4h; then maintenance",
    neonatalDose: "Breast-feed more frequently; ORS generally not recommended in neonates — use IV if needed",
    route: "PO",
    frequency: "Over 4h rehydration then maintenance",
  },

  // ── Analgesics / NSAIDs (additional) ─────────────────────────────
  {
    name: "Mefenamic Acid",
    nameAr: "حمض ميفينامي",
    genericName: "Mefenamic Acid",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "Syrup 50mg: (Wt/2)+1 mL TDS; Tablet: 10 mg/kg/dose BD–TDS (>6 months only)",
    neonatalDose: "Not recommended in neonates",
    route: "PO",
    frequency: "TDS",
    notes: "For children >6 months only",
  },
  {
    name: "Aspirin",
    nameAr: "أسبرين",
    genericName: "Aspirin",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "Anti-inflammatory/antipyretic: 30–80 mg/kg/day ÷ q6h; Kawasaki (high dose): 80–100 mg/kg/day q6h",
    neonatalDose: "Not recommended in neonates",
    route: "PO",
    frequency: "q6h",
    notes: "Avoid in viral illness (Reye syndrome risk); use with caution in children",
  },
  {
    name: "Diclofenac Sodium",
    nameAr: "ديكلوفيناك صوديوم",
    genericName: "Diclofenac Sodium",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "IM: 1 mg/kg/dose TDS–BD (>6 months); Eye drops 0.1%: 1 drop BD × 3 days (>7 years)",
    neonatalDose: "Not recommended",
    route: "IM / Eye drops",
    frequency: "TDS or BD",
    notes: "For >6 months only; IM injection only (not IV)",
  },
  {
    name: "Ketoprofen",
    nameAr: "كيتوبروفين",
    genericName: "Ketoprofen",
    category: "analgesic",
    categoryAr: "مسكنات الألم وخافضات الحرارة",
    pediatricDose: "Syrup: <5 years: 2.5 mL BD; >5 years: 5 mL BD × 5 days",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "BD × 5 days",
  },

  // ── Antibiotics (additional) ──────────────────────────────────────
  {
    name: "Erythromycin",
    nameAr: "إيريثروميسين",
    genericName: "Erythromycin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "Syrup 125 mg: Wt/2 mL BD × 3 days; 250 mg: Wt/4 mL BD × 3 days",
    neonatalDose: "12.5 mg/kg/dose q6h PO (pertussis: 12.5 mg/kg q6h × 14 days)",
    route: "PO",
    frequency: "BD",
  },
  {
    name: "Cefaclor",
    nameAr: "سيفاكلور",
    genericName: "Cefaclor",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "Syrup 125 mg: Wt/2 mL; 250 mg: Wt/4 mL — BD × 7–10 days; Capsule: 20–40 mg/kg/day ÷ BD",
    neonatalDose: "Not recommended <1 month",
    route: "PO",
    frequency: "BD × 7–10 days",
  },
  {
    name: "Cefixime",
    nameAr: "سيفيكسيم",
    genericName: "Cefixime",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "Suspension 100 mg: Wt × 0.4 mL OD–BD × 6 days; Capsule: 8 mg/kg/dose OD × 5–6 days",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD or BD",
  },
  {
    name: "Cefadroxil",
    nameAr: "سيفادروكسيل",
    genericName: "Cefadroxil",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "30 mg/kg/day OD or BD × 10 days (skin/soft tissue, pharyngitis)",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD or BD × 10 days",
  },
  {
    name: "Cefpodoxime",
    nameAr: "سيفبودوكسيم",
    genericName: "Cefpodoxime",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "Syrup 50 mg: Wt/2 mL OD; 100 mg: Wt/4 mL OD; Tablet: 10 mg/kg/day BD × 5–10 days",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD or BD",
  },
  {
    name: "Ceftazidime",
    nameAr: "سيفتازيديم",
    genericName: "Ceftazidime",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "30–50 mg/kg/dose IV/IM BD–TDS (severe infections: 50 mg/kg/dose TDS)",
    neonatalDose: "25–50 mg/kg/dose q8–12h IV",
    route: "IV / IM",
    frequency: "BD or TDS",
  },
  {
    name: "Meropenem",
    nameAr: "ميروبينيم",
    genericName: "Meropenem",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "20 mg/kg/dose TDS IV; Meningitis: 40 mg/kg/dose TDS IV",
    neonatalDose: "20 mg/kg/dose q8–12h IV",
    route: "IV",
    frequency: "TDS",
  },
  {
    name: "Amikacin",
    nameAr: "أميكاسين",
    genericName: "Amikacin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "15–22.5 mg/kg/day IV/IM OD (extended-interval); or 7.5 mg/kg/dose q12h",
    neonatalDose: "15 mg/kg/dose: q48h (<29 wks GA); q36h (29–35 wks); q24h (≥36 wks)",
    route: "IV / IM",
    frequency: "OD or q12h",
    notes: "Monitor levels; nephrotoxic and ototoxic",
  },
  {
    name: "Streptomycin",
    nameAr: "ستربتومايسين",
    genericName: "Streptomycin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "40 mg/kg/day IM OD (TB: 20–40 mg/kg/day; max 1 g/day)",
    neonatalDose: "Not recommended",
    route: "IM",
    frequency: "OD",
    notes: "Monitor for ototoxicity and nephrotoxicity",
  },
  {
    name: "Benzathine Penicillin",
    nameAr: "بنزاثين بنسلين",
    genericName: "Benzathine Benzylpenicillin",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "<7 years: 600,000 IU IM single dose; >7 years: 1,200,000 IU IM single dose; RHD prophylaxis: every 3–4 weeks",
    neonatalDose: "Not recommended",
    route: "IM",
    frequency: "Single dose or every 3–4 weeks (RHD)",
    notes: "Sensitivity test before injection; used for bacterial pharyngitis and RHD prophylaxis",
  },

  // ── Antiparasitics / Antimalarials ────────────────────────────────
  {
    name: "Artesunate",
    nameAr: "أرتيسونات",
    genericName: "Artesunate",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "<20 kg: Wt × 3 mg IV; ≥20 kg: Wt × 2.4 mg IV — q12h × 3 doses then q24h to complete 7 doses",
    neonatalDose: "3 mg/kg/dose IV",
    route: "IV",
    frequency: "q12h (first 3 doses) then q24h",
    notes: "For severe malaria; complete 7 total doses",
  },
  {
    name: "Quinine",
    nameAr: "كينين",
    genericName: "Quinine",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "IV: 10 mg/kg/dose TDS in D10% (1:1 ratio); Oral: 10 mg/kg/dose TDS × 5–7 days",
    neonatalDose: "10 mg/kg/dose q8–12h",
    route: "IV / PO",
    frequency: "TDS",
    notes: "Monitor blood glucose; hypoglycaemia risk with IV infusion",
  },
  {
    name: "Artemether/Lumefantrine (Coartum)",
    nameAr: "أرتيميثر/لوميفانترين (كوارتم)",
    genericName: "Artemether-Lumefantrine",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "<5 kg: 0.5 tab; 5–14 kg: 1 tab; 15–24 kg: 2 tabs; 25–34 kg: 3 tabs; >35 kg: 4 tabs — Now, after 8h, then q12h",
    neonatalDose: "Not recommended <5 kg",
    route: "PO",
    frequency: "Now, after 8h, then q12h × 2 days",
    notes: "Take with fatty food; administer with milk if possible",
  },
  {
    name: "Dihydroartemisinin-Piperaquine (DHAP)",
    nameAr: "ديهيدروأرتيميسينين-بيبيراكين (DHAP)",
    genericName: "Dihydroartemisinin-Piperaquine",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "<5 kg: 0.25 tab; 5–7 kg: 0.5 tab; 8–12 kg: 1 tab; 13–22 kg: 1 tab (adult); 23–35 kg: 2 tabs; 36–74 kg: 3 tabs — OD × 3 days",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD × 3 days",
  },
  {
    name: "Primaquine",
    nameAr: "بريماكين",
    genericName: "Primaquine",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "0.25 mg/kg/dose OD × 14 days (P. vivax/ovale radical cure); G6PD screen before use",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD × 14 days",
    notes: "Screen for G6PD deficiency before use — risk of haemolytic anaemia",
  },
  {
    name: "Mebendazole",
    nameAr: "ميبندازول",
    genericName: "Mebendazole",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: ">2 years: 100 mg BD × 3 days (intestinal helminths); repeat after 2 weeks",
    neonatalDose: "Not recommended <2 years",
    route: "PO",
    frequency: "BD × 3 days",
  },
  {
    name: "Albendazole",
    nameAr: "ألبندازول",
    genericName: "Albendazole",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "15 mg/kg (Wt × 0.7 mL syrup) single dose on empty stomach (>12 months; max 400 mg)",
    neonatalDose: "Not recommended <12 months",
    route: "PO",
    frequency: "Single dose",
    notes: "Give on empty stomach for systemic infections; with food for intestinal infections",
  },
  {
    name: "Secnidazole",
    nameAr: "سيكنيدازول",
    genericName: "Secnidazole",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: ">2 years: 30 mg/kg/day OD × 4 days (amoebiasis/giardiasis)",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD × 4 days",
  },
  {
    name: "Praziquantel",
    nameAr: "برازيكوانتيل",
    genericName: "Praziquantel",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: ">4 years: 40 mg/kg/dose single dose or 3 times in one day; H. nana: 20 mg/kg single dose",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "Single dose or TDS (one day)",
  },

  // ── Respiratory / Mucolytics (additional) ────────────────────────
  {
    name: "Ambroxol",
    nameAr: "أمبروكسول",
    genericName: "Ambroxol",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "<2 years: 1.5 mL TDS × 5 days; 2–5 years: 2.5 mL TDS × 5 days; >5 years: 5–10 mL TDS × 5 days",
    neonatalDose: "Not standard; 0.5–1 mL/dose q12h if prescribed",
    route: "PO",
    frequency: "TDS × 5 days",
  },
  {
    name: "Chlorphenamine (Antihistamine)",
    nameAr: "كلورفينامين (مضاد هيستامين)",
    genericName: "Chlorphenamine",
    category: "respiratory",
    categoryAr: "الجهاز التنفسي",
    pediatricDose: "Syrup 5 mg: Wt × 0.1 mL OD × 5 days; Inj: <2 yrs: 2–5 mg; 2–5 yrs: 5 mg; >5 yrs: 10 mg IM/IV PRN",
    neonatalDose: "Not recommended",
    route: "PO / IV / IM",
    frequency: "OD (syrup) or PRN (injection)",
  },

  // ── GI (additional) ──────────────────────────────────────────────
  {
    name: "Pantoprazole",
    nameAr: "بانتوبرازول",
    genericName: "Pantoprazole",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: ">5 years: initially 20 mg OD before meal; increase as required",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD before meal",
  },
  {
    name: "Simethicone",
    nameAr: "سيميثيكون",
    genericName: "Simethicone",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "<2 years: 20 mg (0.5 mL) q6h; >2 years: 40 mg (1 mL) q6h after feeds",
    neonatalDose: "20 mg/dose (0.5 mL) q6h",
    route: "PO (oral drops)",
    frequency: "q6h",
  },
  {
    name: "Prifinium Bromide (Riabal)",
    nameAr: "بريفينيوم بروميد (ريابال)",
    genericName: "Prifinium Bromide",
    category: "gi",
    categoryAr: "الجهاز الهضمي",
    pediatricDose: "TDS × 3 days (dose per weight on packaging)",
    neonatalDose: "Use with caution; per specialist guidance",
    route: "PO (oral drops)",
    frequency: "TDS × 3 days",
  },

  // ── Hematology / Vitamins (additional) ───────────────────────────
  {
    name: "Vitamin B6 (Pyridoxine)",
    nameAr: "فيتامين ب6 (بيريدوكسين)",
    genericName: "Pyridoxine",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Wt × 50 mg IM/slow IV (seizures); Deficiency: 5–25 mg/day PO",
    neonatalDose: "100 mg IV single dose (pyridoxine-dependent seizures); then 50–100 mg/day PO",
    route: "IM / Slow IV / PO",
    frequency: "Single dose (seizures) or OD",
  },
  {
    name: "Vitamin B12 (Cyanocobalamin)",
    nameAr: "فيتامين ب12 (سيانوكوبالامين)",
    genericName: "Cyanocobalamin",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Wt × 15–30 mcg IM × 5 times/week × 2–4 weeks; Pernicious anaemia: 100 mcg IM monthly",
    neonatalDose: "Not standard; specialist guidance",
    route: "IM",
    frequency: "5×/week × 2–4 weeks, then monthly",
  },
  {
    name: "Deferoxamine",
    nameAr: "ديفيروكسامين",
    genericName: "Deferoxamine",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Iron overload (thalassaemia): 15 mg/kg/h SC infusion over 8–12h; max 40 mg/kg/day",
    neonatalDose: "Not recommended",
    route: "SC / IV infusion",
    frequency: "5–7 nights/week",
    notes: "Subcutaneous pump preferred; monitor auditory and visual function",
  },
  {
    name: "Hydroxyurea",
    nameAr: "هيدروكسيوريا",
    genericName: "Hydroxyurea",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Sickle cell: 15–20 mg/kg/day OD, increase by 5 mg/kg/day every 8 weeks (max 35 mg/kg/day)",
    neonatalDose: "Not recommended",
    route: "PO",
    frequency: "OD",
    notes: "Specialist initiation only; monitor FBC every 4–8 weeks; hold if ANC <2000 or platelets <80,000",
  },

  // ── Emergency (additional) ────────────────────────────────────────
  {
    name: "Magnesium Sulphate",
    nameAr: "كبريتات المغنيسيوم",
    genericName: "Magnesium Sulphate",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Hypomagnesaemia / severe asthma: 25–50 mg/kg/dose IV over 10–20 min; max 2 g/dose",
    neonatalDose: "25–50 mg/kg/dose IV slow infusion",
    route: "IV",
    frequency: "Single dose or per deficit",
    notes: "Monitor respiratory status; calcium gluconate available as antidote",
  },
  {
    name: "Mannitol",
    nameAr: "مانيتول",
    genericName: "Mannitol",
    category: "emergency",
    categoryAr: "الطوارئ والإنعاش",
    pediatricDose: "Raised ICP: 0.25–1 g/kg IV over 15–30 min; repeat q4–6h as needed",
    neonatalDose: "0.25–0.5 g/kg IV over 30–60 min (use with caution)",
    route: "IV infusion",
    frequency: "q4–6h PRN",
    notes: "Use 20% solution; monitor serum osmolality (target <320 mOsm/kg)",
  },
  {
    name: "Vitamin K Injection",
    nameAr: "فيتامين ك حقن",
    genericName: "Phytomenadione",
    category: "hematology",
    categoryAr: "أمراض الدم والفيتامينات",
    pediatricDose: "Prophylactic: 1 mg IM at birth; Therapeutic: 1 mg/kg/day IV/IM OD × 3–5 days",
    neonatalDose: "≥1 kg: 1 mg IM; <1 kg: 0.5 mg IM at birth",
    route: "IM / IV",
    frequency: "Single dose (prophylaxis) or OD × 3–5 days (therapeutic)",
  },

  // ── Antifungals / Topical ─────────────────────────────────────────
  {
    name: "Clotrimazole",
    nameAr: "كلوتريمازول",
    genericName: "Clotrimazole",
    category: "antiviral",
    categoryAr: "مضادات الفيروسات والفطريات",
    pediatricDose: "Ear drops 1% (Candid): 3–4 drops TDS × 5–7 days",
    neonatalDose: "Use with caution",
    route: "Ear drops",
    frequency: "TDS × 5–7 days",
  },
  {
    name: "Chloramphenicol (Eye/Ear)",
    nameAr: "كلورامفينيكول (قطرة عين/أذن)",
    genericName: "Chloramphenicol",
    category: "antibiotic",
    categoryAr: "المضادات الحيوية",
    pediatricDose: "Eye drops 0.5%: 1–2 drops BD × 5 days (conjunctivitis)",
    neonatalDose: "1 drop per eye BD (ophthalmia neonatorum prophylaxis — specialist guidance)",
    route: "Eye drops",
    frequency: "BD × 5 days",
  },
];

// ─── Hospital Drug List (from official dose reference sheet) ─────────────────
// Flat list of all drugs stocked at Almuzini Children Hospital, used for the
// inline drug-name combobox in the prescription form.

export type DrugForm = "injection" | "syrup" | "drop" | "tablet";

export interface HospitalDrug {
  name: string;
  nameAr: string;
  form: DrugForm;
  genericName?: string;
  refKey?: string; // matches DRUG_REFERENCE[].name for dose auto-fill
}

export const HOSPITAL_DRUG_LIST: HospitalDrug[] = [
  // ── Injections / Infusions ──────────────────────────────────────────────────
  { name: "Diazepam Injection (IV / Per Rectal)",     nameAr: "ديازيبام حقن",                form: "injection", genericName: "Diazepam",          refKey: "Diazepam" },
  { name: "Phenytoin Injection",                       nameAr: "فينيتوين حقن",               form: "injection", genericName: "Phenytoin",          refKey: "Phenytoin (Diphenylhydantoin)" },
  { name: "Midazolam Injection",                       nameAr: "ميدازولام حقن",              form: "injection", genericName: "Midazolam",          refKey: "Midazolam" },
  { name: "Chlorphenamine Injection (Antihistamine)",  nameAr: "كلورفينامين حقن",            form: "injection", genericName: "Chlorphenamine",     refKey: "Chlorphenamine (Antihistamine)" },
  { name: "Dexamethasone Injection",                   nameAr: "ديكساميتازون حقن",           form: "injection", genericName: "Dexamethasone",      refKey: "Dexamethasone" },
  { name: "Adrenaline (Epinephrine) Injection",        nameAr: "أدرينالين حقن",              form: "injection", genericName: "Epinephrine",        refKey: "Adrenaline (Epinephrine) IV/IO" },
  { name: "Hydrocortisone Injection",                  nameAr: "هيدروكورتيزون حقن",          form: "injection", genericName: "Hydrocortisone",     refKey: "Hydrocortisone" },
  { name: "Furosemide (Lasix) Injection",              nameAr: "فوروسيميد (لاسيكس) حقن",    form: "injection", genericName: "Furosemide",         refKey: "Furosemide (Frusemide)" },
  { name: "Vitamin K Injection",                       nameAr: "فيتامين ك حقن",              form: "injection", genericName: "Phytomenadione",     refKey: "Vitamin K Injection" },
  { name: "Vitamin B6 (Pyridoxine) Injection",         nameAr: "فيتامين ب6 حقن",             form: "injection", genericName: "Pyridoxine",         refKey: "Vitamin B6 (Pyridoxine)" },
  { name: "Vitamin B12 Injection",                     nameAr: "فيتامين ب12 حقن",            form: "injection", genericName: "Cyanocobalamin",     refKey: "Vitamin B12 (Cyanocobalamin)" },
  { name: "Ondansetron Injection",                     nameAr: "أوندانسيترون حقن",           form: "injection", genericName: "Ondansetron",        refKey: "Ondansetron" },
  { name: "Calcium Gluconate 10% Injection",           nameAr: "جلوكونات الكالسيوم حقن",    form: "injection", genericName: "Calcium Gluconate",  refKey: "Calcium Gluconate" },
  { name: "Paracetamol IV Infusion",                   nameAr: "باراسيتامول تسريب وريدي",   form: "injection", genericName: "Paracetamol",        refKey: "Paracetamol (Acetaminophen)" },
  { name: "Diclofenac Sodium (Voltarol) Injection",    nameAr: "ديكلوفيناك صوديوم حقن",     form: "injection", genericName: "Diclofenac Sodium",  refKey: "Diclofenac Sodium" },
  { name: "Benzyl Penicillin Injection",               nameAr: "بنزيل بنسلين حقن",           form: "injection", genericName: "Benzylpenicillin",   refKey: "Benzylpenicillin (Penicillin G)" },
  { name: "Benzathine Penicillin Injection",           nameAr: "بنزاثين بنسلين حقن",         form: "injection", genericName: "Benzathine Benzylpenicillin", refKey: "Benzathine Penicillin" },
  { name: "Ampicillin Injection",                      nameAr: "أمبيسيلين حقن",              form: "injection", genericName: "Ampicillin",         refKey: "Ampicillin" },
  { name: "Gentamicin Injection",                      nameAr: "جنتاميسين حقن",              form: "injection", genericName: "Gentamicin",         refKey: "Gentamicin" },
  { name: "Vancomycin Injection",                      nameAr: "فانكوميسين حقن",             form: "injection", genericName: "Vancomycin",         refKey: "Vancomycin" },
  { name: "Artesunate Injection",                      nameAr: "أرتيسونات حقن",              form: "injection", genericName: "Artesunate",         refKey: "Artesunate" },
  { name: "Quinine Injection",                         nameAr: "كينين حقن",                  form: "injection", genericName: "Quinine",            refKey: "Quinine" },
  { name: "Acyclovir Injection",                       nameAr: "أسيكلوفير حقن",              form: "injection", genericName: "Acyclovir",          refKey: "Acyclovir" },
  { name: "Cefotaxime Injection",                      nameAr: "سيفوتاكسيم حقن",             form: "injection", genericName: "Cefotaxime",         refKey: "Cefotaxime" },
  { name: "Ceftriaxone (Samixon) Injection",           nameAr: "سيفترياكسون (سامكسون) حقن", form: "injection", genericName: "Ceftriaxone",        refKey: "Ceftriaxone" },
  { name: "Cefuroxime (Maxil) Injection",              nameAr: "سيفوروكسيم (ماكسيل) حقن",   form: "injection", genericName: "Cefuroxime",         refKey: "Cefuroxime" },
  { name: "Ceftazidime (Fortum) Injection",            nameAr: "سيفتازيديم (فورتوم) حقن",   form: "injection", genericName: "Ceftazidime",        refKey: "Ceftazidime" },
  { name: "Aminophylline Injection",                   nameAr: "أمينوفيلين حقن",             form: "injection", genericName: "Aminophylline",      refKey: "Aminophylline" },
  { name: "Magnesium Sulphate Injection",              nameAr: "كبريتات المغنيسيوم حقن",    form: "injection", genericName: "Magnesium Sulphate", refKey: "Magnesium Sulphate" },
  { name: "Anti-Tetanus Injection (Tetanus Toxoid)",   nameAr: "حقن الكزاز الوقائي",         form: "injection", genericName: "Tetanus Toxoid" },
  { name: "Tetanus Immunoglobulin",                    nameAr: "غلوبيولين الكزاز العلاجي",  form: "injection", genericName: "Tetanus Immunoglobulin" },
  { name: "Anti-Venom Injection",                      nameAr: "مضاد السموم حقن",            form: "injection", genericName: "Anti-Venom" },
  { name: "Anti-Rabies Injection",                     nameAr: "مضاد داء الكلب حقن",         form: "injection", genericName: "Rabies Immunoglobulin" },
  { name: "Metronidazole IV Infusion",                 nameAr: "ميترونيدازول تسريب وريدي",  form: "injection", genericName: "Metronidazole",      refKey: "Metronidazole" },
  { name: "Streptomycin Injection",                    nameAr: "ستربتومايسين حقن",           form: "injection", genericName: "Streptomycin",       refKey: "Streptomycin" },
  { name: "Deferoxamine Mesilate Infusion",            nameAr: "دیفيروكسامين ميسيلات تسريب",form: "injection", genericName: "Deferoxamine",       refKey: "Deferoxamine" },
  { name: "Morphine Injection",                        nameAr: "مورفين حقن",                 form: "injection", genericName: "Morphine",           refKey: "Morphine Sulfate" },
  { name: "Meropenem Injection",                       nameAr: "ميروبينيم حقن",              form: "injection", genericName: "Meropenem",          refKey: "Meropenem" },
  { name: "Mannitol IV Infusion",                      nameAr: "مانيتول تسريب وريدي",        form: "injection", genericName: "Mannitol",           refKey: "Mannitol" },
  { name: "Amikacin Injection",                        nameAr: "أميكاسين حقن",               form: "injection", genericName: "Amikacin",           refKey: "Amikacin" },

  // ── Syrups / Suspensions ────────────────────────────────────────────────────
  { name: "Paracetamol Syrup 120mg",                   nameAr: "باراسيتامول شراب 120مج",    form: "syrup",     genericName: "Paracetamol",        refKey: "Paracetamol (Acetaminophen)" },
  { name: "Mefenamic Acid Syrup 50mg",                 nameAr: "حمض ميفينامي شراب 50مج",    form: "syrup",     genericName: "Mefenamic Acid",     refKey: "Mefenamic Acid" },
  { name: "Ibuprofen Syrup 100mg",                     nameAr: "إيبوبروفين شراب 100مج",     form: "syrup",     genericName: "Ibuprofen",          refKey: "Ibuprofen" },
  { name: "Balsam Cough Syrup",                        nameAr: "شراب بلسم للكحة",            form: "syrup",     genericName: "Balsam" },
  { name: "Histalix PD Syrup",                         nameAr: "هيستاليكس شراب للأطفال",    form: "syrup",     genericName: "Antihistamine Cough Syrup", refKey: "Chlorphenamine (Antihistamine)" },
  { name: "Amilyn PD Syrup",                           nameAr: "أميلين شراب للأطفال",        form: "syrup",     genericName: "Antihistamine Cough Syrup", refKey: "Chlorphenamine (Antihistamine)" },
  { name: "Prospan Cough Syrup",                       nameAr: "بروسبان شراب للكحة",         form: "syrup",     genericName: "Ivy Leaf Extract" },
  { name: "Pulmocare Syrup",                           nameAr: "بولموكار شراب",              form: "syrup",     genericName: "Ambroxol",           refKey: "Ambroxol" },
  { name: "Ambolar Syrup",                             nameAr: "أمبولار شراب",               form: "syrup",     genericName: "Ambroxol",           refKey: "Ambroxol" },
  { name: "Solvexin Syrup",                            nameAr: "سولفكسين شراب",              form: "syrup",     genericName: "Ambroxol",           refKey: "Ambroxol" },
  { name: "Bronchophane Syrup",                        nameAr: "برونكوفان شراب",             form: "syrup",     genericName: "Ambroxol",           refKey: "Ambroxol" },
  { name: "Amoxicillin Syrup 125mg",                   nameAr: "أموكسيسيلين شراب 125مج",    form: "syrup",     genericName: "Amoxicillin",        refKey: "Amoxicillin" },
  { name: "Amoxicillin Syrup 250mg",                   nameAr: "أموكسيسيلين شراب 250مج",    form: "syrup",     genericName: "Amoxicillin",        refKey: "Amoxicillin" },
  { name: "Amoclan Syrup 200mg (Co-Amoxiclav)",        nameAr: "أموكلان شراب 200مج",         form: "syrup",     genericName: "Amoxicillin-Clavulanate", refKey: "Co-Amoxiclav (Amoxicillin-Clavulanate)" },
  { name: "Amoclan Syrup 400mg (Co-Amoxiclav)",        nameAr: "أموكلان شراب 400مج",         form: "syrup",     genericName: "Amoxicillin-Clavulanate", refKey: "Co-Amoxiclav (Amoxicillin-Clavulanate)" },
  { name: "Ampiclox Suspension 250mg",                 nameAr: "أمبيكلوكس معلق 250مج",      form: "syrup",     genericName: "Ampicillin-Cloxacillin" },
  { name: "Azithromycin Suspension 200mg",             nameAr: "أزيثروميسين معلق 200مج",    form: "syrup",     genericName: "Azithromycin",       refKey: "Azithromycin" },
  { name: "Erythromycin Syrup 125mg",                  nameAr: "إيريثروميسين شراب 125مج",   form: "syrup",     genericName: "Erythromycin",       refKey: "Erythromycin" },
  { name: "Erythromycin Syrup 250mg",                  nameAr: "إيريثروميسين شراب 250مج",   form: "syrup",     genericName: "Erythromycin",       refKey: "Erythromycin" },
  { name: "Clarithromycin Syrup 125mg",                nameAr: "كلاريثروميسين شراب 125مج",  form: "syrup",     genericName: "Clarithromycin",     refKey: "Clarithromycin" },
  { name: "Clarithromycin Syrup 250mg",                nameAr: "كلاريثروميسين شراب 250مج",  form: "syrup",     genericName: "Clarithromycin",     refKey: "Clarithromycin" },
  { name: "Cefaclor Syrup 125mg",                      nameAr: "سيفاكلور شراب 125مج",       form: "syrup",     genericName: "Cefaclor",           refKey: "Cefaclor" },
  { name: "Cefaclor Syrup 250mg",                      nameAr: "سيفاكلور شراب 250مج",       form: "syrup",     genericName: "Cefaclor",           refKey: "Cefaclor" },
  { name: "Cefixime Suspension 100mg",                 nameAr: "سيفيكسيم معلق 100مج",       form: "syrup",     genericName: "Cefixime",           refKey: "Cefixime" },
  { name: "Cephalexin (Cefalixin) Syrup 125mg",        nameAr: "سيفاليكسين شراب 125مج",     form: "syrup",     genericName: "Cephalexin",         refKey: "Cephalexin" },
  { name: "Cephalexin (Cefalixin) Syrup 250mg",        nameAr: "سيفاليكسين شراب 250مج",     form: "syrup",     genericName: "Cephalexin",         refKey: "Cephalexin" },
  { name: "Cefpodoxime (Cefedox) Syrup 50mg",          nameAr: "سيفبودوكسيم شراب 50مج",     form: "syrup",     genericName: "Cefpodoxime",        refKey: "Cefpodoxime" },
  { name: "Cefpodoxime (Cefedox) Syrup 100mg",         nameAr: "سيفبودوكسيم شراب 100مج",    form: "syrup",     genericName: "Cefpodoxime",        refKey: "Cefpodoxime" },
  { name: "Ketoprofen (Ketofen) Syrup",                nameAr: "كيتوبروفين شراب",            form: "syrup",     genericName: "Ketoprofen",         refKey: "Ketoprofen" },
  { name: "Chlorphenamine (Antihistamine) Syrup 5mg",  nameAr: "كلورفينامين شراب 5مج",      form: "syrup",     genericName: "Chlorphenamine",     refKey: "Chlorphenamine (Antihistamine)" },
  { name: "Salbutamol Syrup 2mg",                      nameAr: "سالبوتامول شراب 2مج",        form: "syrup",     genericName: "Salbutamol",         refKey: "Salbutamol (Albuterol)" },
  { name: "Metronidazole Syrup 200mg",                 nameAr: "ميترونيدازول شراب 200مج",   form: "syrup",     genericName: "Metronidazole",      refKey: "Metronidazole" },
  { name: "Zinc Sulphate Syrup",                       nameAr: "كبريتات الزنك شراب",         form: "syrup",     genericName: "Zinc Sulphate" },
  { name: "Lactulose Syrup 10mg",                      nameAr: "لاكتولوز شراب 10مج",        form: "syrup",     genericName: "Lactulose",          refKey: "Lactulose" },
  { name: "Ferrous Sulphate (Saferron) Syrup",         nameAr: "كبريتات الحديد (سافيرون) شراب", form: "syrup", genericName: "Ferrous Sulphate",   refKey: "Iron (Ferrous Sulfate)" },
  { name: "Hematin Syrup",                             nameAr: "هيماتين شراب",               form: "syrup",     genericName: "Iron Protein Succinylate" },
  { name: "Dexamethasone (Orazone) Syrup",             nameAr: "ديكساميتازون (أوروزون) شراب", form: "syrup",   genericName: "Dexamethasone",      refKey: "Dexamethasone" },
  { name: "Mebendazole (Vermox) Syrup 100mg",          nameAr: "ميبندازول (فيرموكس) شراب",  form: "syrup",     genericName: "Mebendazole",        refKey: "Mebendazole" },
  { name: "Albendazole Syrup 100mg",                   nameAr: "ألبندازول شراب 100مج",       form: "syrup",     genericName: "Albendazole",        refKey: "Albendazole" },
  { name: "Co-Trimoxazole (Septrin) Syrup 240mg",      nameAr: "كوتريموكسازول (سبترين) شراب", form: "syrup",  genericName: "Trimethoprim-Sulfamethoxazole", refKey: "Co-trimoxazole (TMP-SMX)" },
  { name: "Carbamazepine (Tegretol) Syrup",            nameAr: "كاربامازيبين (تيجريتول) شراب", form: "syrup", genericName: "Carbamazepine",      refKey: "Carbamazepine" },
  { name: "Acyclovir Syrup 200mg",                     nameAr: "أسيكلوفير شراب 200مج",       form: "syrup",     genericName: "Acyclovir",          refKey: "Acyclovir" },
  { name: "Domperidone Syrup",                         nameAr: "دومبيريدون شراب",            form: "syrup",     genericName: "Domperidone",        refKey: "Domperidone" },

  // ── Oral / Ear / Eye / Nasal Drops ──────────────────────────────────────────
  { name: "Paracetamol (Adol) Oral Drops 100mg/ml",   nameAr: "باراسيتامول (أدول) قطرة",   form: "drop",      genericName: "Paracetamol",        refKey: "Paracetamol (Acetaminophen)" },
  { name: "Nystatin (Fungistatin) Oral Drops",         nameAr: "نيستاتين (فنجيستاتين) قطرة",form: "drop",      genericName: "Nystatin",           refKey: "Nystatin" },
  { name: "Vitamin D3 (Infa D) Oral Drops 1000 IU",   nameAr: "فيتامين د3 (إنفا دي) قطرة", form: "drop",      genericName: "Cholecalciferol" },
  { name: "Prifinium Bromide (Riabal) Oral Drops",     nameAr: "بريفينيوم بروميد (ريابال) قطرة", form: "drop", genericName: "Prifinium Bromide", refKey: "Prifinium Bromide (Riabal)" },
  { name: "Simethicone (Disflatyl/Infacon) Drops",     nameAr: "سيميثيكون (ديسفلاتيل) قطرة",form: "drop",     genericName: "Simethicone",        refKey: "Simethicone" },
  { name: "Folic Acid (Foliclap) Oral Drops",          nameAr: "حمض الفوليك قطرة",           form: "drop",      genericName: "Folic Acid" },
  { name: "Ivylex Herbal Cough Oral Drops",            nameAr: "أيفيليكس قطرة عشبية للكحة", form: "drop",      genericName: "Ivy Leaf Extract" },
  { name: "Miniguava Herbal Cough Oral Drops",         nameAr: "ميني جوافة قطرة عشبية للكحة", form: "drop",    genericName: "Guava Leaf Extract" },
  { name: "Iron (Fer-Sol) Oral Drops",                 nameAr: "حديد (فير-سول) قطرة",        form: "drop",      genericName: "Iron III Hydroxide",  refKey: "Iron (Ferrous Sulfate)" },
  { name: "Clotrimazole (Candid) 1% Ear Drops",       nameAr: "كلوتريمازول (كانديد) قطرة أذن", form: "drop",  genericName: "Clotrimazole",       refKey: "Clotrimazole" },
  { name: "Gentamicin (Apigen) Ear/Eye Drops",        nameAr: "جنتاميسين (أبيجن) قطرة أذن/عين", form: "drop", genericName: "Gentamicin",         refKey: "Gentamicin" },
  { name: "Sodium Bicarbonate Ear Drops",              nameAr: "بيكربونات الصوديوم قطرة أذن", form: "drop",    genericName: "Sodium Bicarbonate" },
  { name: "Ciprofloxacin 0.3% Eye Drops",             nameAr: "سيبروفلوكساسين 0.3% قطرة عين", form: "drop",  genericName: "Ciprofloxacin",      refKey: "Ciprofloxacin" },
  { name: "Chloramphenicol (Isomephenicol) 0.5% Eye Drops", nameAr: "كلورامفينيكول قطرة عين 0.5%", form: "drop", genericName: "Chloramphenicol",  refKey: "Chloramphenicol (Eye/Ear)" },
  { name: "Diclofenac (Diclogesic) 0.1% Eye Drops",   nameAr: "ديكلوفيناك (ديكلوجيزيك) قطرة عين", form: "drop", genericName: "Diclofenac Sodium", refKey: "Diclofenac Sodium" },

  // ── Tablets / Capsules ──────────────────────────────────────────────────────
  { name: "Paracetamol 250mg Tablet",                  nameAr: "باراسيتامول 250مج قرص",     form: "tablet",    genericName: "Paracetamol",        refKey: "Paracetamol (Acetaminophen)" },
  { name: "Paracetamol 500mg Tablet",                  nameAr: "باراسيتامول 500مج قرص",     form: "tablet",    genericName: "Paracetamol",        refKey: "Paracetamol (Acetaminophen)" },
  { name: "Ibuprofen 200mg Tablet",                    nameAr: "إيبوبروفين 200مج قرص",      form: "tablet",    genericName: "Ibuprofen",          refKey: "Ibuprofen" },
  { name: "Ibuprofen 400mg Tablet",                    nameAr: "إيبوبروفين 400مج قرص",      form: "tablet",    genericName: "Ibuprofen",          refKey: "Ibuprofen" },
  { name: "Mefenamic Acid 250mg Tablet",               nameAr: "حمض ميفينامي 250مج قرص",   form: "tablet",    genericName: "Mefenamic Acid",     refKey: "Mefenamic Acid" },
  { name: "Mefenamic Acid 500mg Tablet",               nameAr: "حمض ميفينامي 500مج قرص",   form: "tablet",    genericName: "Mefenamic Acid",     refKey: "Mefenamic Acid" },
  { name: "Aspirin 75mg Tablet",                       nameAr: "أسبرين 75مج قرص",           form: "tablet",    genericName: "Aspirin",            refKey: "Aspirin" },
  { name: "Aspirin 100mg Tablet",                      nameAr: "أسبرين 100مج قرص",          form: "tablet",    genericName: "Aspirin",            refKey: "Aspirin" },
  { name: "Aspirin 300mg Tablet",                      nameAr: "أسبرين 300مج قرص",          form: "tablet",    genericName: "Aspirin",            refKey: "Aspirin" },
  { name: "Prednisolone 5mg Tablet",                   nameAr: "بريدنيزولون 5مج قرص",       form: "tablet",    genericName: "Prednisolone",       refKey: "Prednisolone" },
  { name: "Amoclan 375mg Capsule (Co-Amoxiclav)",      nameAr: "أموكلان 375مج كبسول",       form: "tablet",    genericName: "Amoxicillin-Clavulanate", refKey: "Co-Amoxiclav (Amoxicillin-Clavulanate)" },
  { name: "Amoclan 625mg Capsule (Co-Amoxiclav)",      nameAr: "أموكلان 625مج كبسول",       form: "tablet",    genericName: "Amoxicillin-Clavulanate", refKey: "Co-Amoxiclav (Amoxicillin-Clavulanate)" },
  { name: "Amoclan 1g Capsule (Co-Amoxiclav)",         nameAr: "أموكلان 1جم كبسول",         form: "tablet",    genericName: "Amoxicillin-Clavulanate", refKey: "Co-Amoxiclav (Amoxicillin-Clavulanate)" },
  { name: "Amoxicillin 250mg Capsule",                 nameAr: "أموكسيسيلين 250مج كبسول",   form: "tablet",    genericName: "Amoxicillin",            refKey: "Amoxicillin" },
  { name: "Amoxicillin 500mg Capsule",                 nameAr: "أموكسيسيلين 500مج كبسول",   form: "tablet",    genericName: "Amoxicillin",            refKey: "Amoxicillin" },
  { name: "Azithromycin 250mg Tablet/Capsule",         nameAr: "أزيثروميسين 250مج قرص/كبسول", form: "tablet",  genericName: "Azithromycin",           refKey: "Azithromycin" },
  { name: "Azithromycin 500mg Tablet/Capsule",         nameAr: "أزيثروميسين 500مج قرص/كبسول", form: "tablet",  genericName: "Azithromycin",           refKey: "Azithromycin" },
  { name: "Cefaclor 250mg Capsule",                    nameAr: "سيفاكلور 250مج كبسول",       form: "tablet",    genericName: "Cefaclor",               refKey: "Cefaclor" },
  { name: "Cefaclor 500mg Capsule",                    nameAr: "سيفاكلور 500مج كبسول",       form: "tablet",    genericName: "Cefaclor",               refKey: "Cefaclor" },
  { name: "Cefalexin 250mg Capsule",                   nameAr: "سيفاليكسين 250مج كبسول",     form: "tablet",    genericName: "Cephalexin",             refKey: "Cephalexin" },
  { name: "Cefalexin 500mg Capsule",                   nameAr: "سيفاليكسين 500مج كبسول",     form: "tablet",    genericName: "Cephalexin",             refKey: "Cephalexin" },
  { name: "Cefixime 200mg Capsule",                    nameAr: "سيفيكسيم 200مج كبسول",       form: "tablet",    genericName: "Cefixime",               refKey: "Cefixime" },
  { name: "Cefixime 400mg Capsule",                    nameAr: "سيفيكسيم 400مج كبسول",       form: "tablet",    genericName: "Cefixime",               refKey: "Cefixime" },
  { name: "Cefuroxime 250mg Tablet",                   nameAr: "سيفوروكسيم 250مج قرص",       form: "tablet",    genericName: "Cefuroxime",             refKey: "Cefuroxime" },
  { name: "Cefuroxime 500mg Tablet",                   nameAr: "سيفوروكسيم 500مج قرص",       form: "tablet",    genericName: "Cefuroxime",             refKey: "Cefuroxime" },
  { name: "Cefadroxil 500mg Capsule",                  nameAr: "سيفادروكسيل 500مج كبسول",    form: "tablet",    genericName: "Cefadroxil",             refKey: "Cefadroxil" },
  { name: "Cefpodoxime 100mg Tablet",                  nameAr: "سيفبودوكسيم 100مج قرص",      form: "tablet",    genericName: "Cefpodoxime",            refKey: "Cefpodoxime" },
  { name: "Cefpodoxime 200mg Tablet",                  nameAr: "سيفبودوكسيم 200مج قرص",      form: "tablet",    genericName: "Cefpodoxime",            refKey: "Cefpodoxime" },
  { name: "Acyclovir 200mg Tablet",                    nameAr: "أسيكلوفير 200مج قرص",         form: "tablet",    genericName: "Acyclovir",              refKey: "Acyclovir" },
  { name: "Acyclovir 400mg Tablet",                    nameAr: "أسيكلوفير 400مج قرص",         form: "tablet",    genericName: "Acyclovir",              refKey: "Acyclovir" },
  { name: "Metronidazole 250mg Tablet",                nameAr: "ميترونيدازول 250مج قرص",      form: "tablet",    genericName: "Metronidazole",          refKey: "Metronidazole" },
  { name: "Metronidazole 500mg Tablet",                nameAr: "ميترونيدازول 500مج قرص",      form: "tablet",    genericName: "Metronidazole",          refKey: "Metronidazole" },
  { name: "Artemether/Lumefantrine (Coartum) 20/120mg Tablet", nameAr: "أرتيميثر/لوميفانترين (كوارتم) 20/120مج", form: "tablet", genericName: "Artemether-Lumefantrine", refKey: "Artemether/Lumefantrine (Coartum)" },
  { name: "Artemether/Lumefantrine (Coartum) 40/480mg Tablet", nameAr: "أرتيميثر/لوميفانترين (كوارتم) 40/480مج", form: "tablet", genericName: "Artemether-Lumefantrine", refKey: "Artemether/Lumefantrine (Coartum)" },
  { name: "DHAP 20/160mg Tablet",                      nameAr: "DHAP 20/160مج قرص",           form: "tablet",    genericName: "Dihydroartemisinin-Piperaquine", refKey: "Dihydroartemisinin-Piperaquine (DHAP)" },
  { name: "DHAP 40/320mg Tablet",                      nameAr: "DHAP 40/320مج قرص",           form: "tablet",    genericName: "Dihydroartemisinin-Piperaquine", refKey: "Dihydroartemisinin-Piperaquine (DHAP)" },
  { name: "Primaquine 7.5mg Tablet",                   nameAr: "بريماكين 7.5مج قرص",          form: "tablet",    genericName: "Primaquine",             refKey: "Primaquine" },
  { name: "Primaquine 15mg Tablet",                    nameAr: "بريماكين 15مج قرص",           form: "tablet",    genericName: "Primaquine",             refKey: "Primaquine" },
  { name: "Quinine 300mg Tablet",                      nameAr: "كينين 300مج قرص",             form: "tablet",    genericName: "Quinine",                refKey: "Quinine" },
  { name: "Mebendazole 100mg Tablet",                  nameAr: "ميبندازول 100مج قرص",         form: "tablet",    genericName: "Mebendazole",            refKey: "Mebendazole" },
  { name: "Albendazole 200mg Tablet",                  nameAr: "ألبندازول 200مج قرص",         form: "tablet",    genericName: "Albendazole",            refKey: "Albendazole" },
  { name: "Secnidazole (Senagyl) 500mg Tablet",        nameAr: "سيكنيدازول (سيناجيل) 500مج", form: "tablet",    genericName: "Secnidazole",            refKey: "Secnidazole" },
  { name: "Praziquantel 600mg Tablet",                 nameAr: "برازيكوانتيل 600مج قرص",      form: "tablet",    genericName: "Praziquantel",           refKey: "Praziquantel" },
  { name: "Omeprazole 20mg Tablet",                    nameAr: "أوميبرازول 20مج قرص",         form: "tablet",    genericName: "Omeprazole",             refKey: "Omeprazole" },
  { name: "Omeprazole 40mg Tablet",                    nameAr: "أوميبرازول 40مج قرص",         form: "tablet",    genericName: "Omeprazole",             refKey: "Omeprazole" },
  { name: "Pantoprazole 20mg Tablet",                  nameAr: "بانتوبرازول 20مج قرص",        form: "tablet",    genericName: "Pantoprazole",           refKey: "Pantoprazole" },
  { name: "Pantoprazole 40mg Tablet",                  nameAr: "بانتوبرازول 40مج قرص",        form: "tablet",    genericName: "Pantoprazole",           refKey: "Pantoprazole" },
  { name: "Folic Acid 5mg Tablet",                     nameAr: "حمض الفوليك 5مج قرص",         form: "tablet",    genericName: "Folic Acid",             refKey: "Folic Acid" },
  { name: "Furosemide (Lasix) 40mg Tablet",            nameAr: "فوروسيميد (لاسيكس) 40مج قرص", form: "tablet",   genericName: "Furosemide",             refKey: "Furosemide (Frusemide)" },
  { name: "Spironolactone (Aldactone) 25mg Tablet",    nameAr: "سبيرونولاكتون (ألداكتون) 25مج", form: "tablet",  genericName: "Spironolactone",         refKey: "Spironolactone" },
  { name: "Spironolactone (Aldactone) 50mg Tablet",    nameAr: "سبيرونولاكتون (ألداكتون) 50مج", form: "tablet",  genericName: "Spironolactone",         refKey: "Spironolactone" },
  { name: "Spironolactone (Aldactone) 100mg Tablet",   nameAr: "سبيرونولاكتون (ألداكتون) 100مج", form: "tablet", genericName: "Spironolactone",         refKey: "Spironolactone" },
  { name: "Phenobarbitone 30mg Tablet",                nameAr: "فينوباربيتون 30مج قرص",        form: "tablet",    genericName: "Phenobarbital",          refKey: "Phenobarbital" },
  { name: "Sodium Valproate (Epilim) 200mg Tablet",    nameAr: "فالبروات الصوديوم (إيبيليم) 200مج", form: "tablet", genericName: "Sodium Valproate",     refKey: "Sodium Valproate (Valproic Acid)" },
  { name: "Sodium Valproate (Epilim) 500mg Tablet",    nameAr: "فالبروات الصوديوم (إيبيليم) 500مج", form: "tablet", genericName: "Sodium Valproate",     refKey: "Sodium Valproate (Valproic Acid)" },
  { name: "Hydroxyurea 500mg Capsule",                 nameAr: "هيدروكسيوريا 500مج كبسول",    form: "tablet",    genericName: "Hydroxyurea",            refKey: "Hydroxyurea" },
];

export function searchHospitalDrugs(query: string): HospitalDrug[] {
  if (!query.trim()) return HOSPITAL_DRUG_LIST;
  const q = query.toLowerCase().trim();
  return HOSPITAL_DRUG_LIST.filter(d =>
    d.name.toLowerCase().includes(q) ||
    d.nameAr.includes(q) ||
    (d.genericName?.toLowerCase().includes(q) ?? false)
  );
}

export function getHospitalDrugByName(name: string): HospitalDrug | undefined {
  return HOSPITAL_DRUG_LIST.find(d => d.name === name);
}

// ─── End Hospital Drug List ───────────────────────────────────────────────────

export function searchDrugs(query: string): DrugReference[] {
  const q = query.toLowerCase().trim();
  if (!q) return DRUG_REFERENCE;
  return DRUG_REFERENCE.filter(d =>
    d.name.toLowerCase().includes(q) ||
    d.nameAr.includes(q) ||
    d.genericName.toLowerCase().includes(q) ||
    d.category.toLowerCase().includes(q) ||
    d.categoryAr.includes(q)
  );
}

export function getDrugsByCategory(category: string): DrugReference[] {
  return DRUG_REFERENCE.filter(d => d.category === category);
}
